[env]
TERM = "xterm-256color"

[window]
#dynamic_padding = true
#decorations = "buttonless"
dynamic_title = true
opacity = 0.4
blur = true

[window.dimensions]
columns = 96
lines = 26

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono"}
bold_italic = { family = "CaskaydiaCove Nerd Font Mono"}
size = 15

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
